name: Trigger auto deployment for apiforapp-vecirrpopxlz2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/apiforapp-vecirrpopxlz2-AutoDeployTrigger-53b9dd54-df4b-4497-85c4-85d48cfb1716.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APIFORAPPVECIRRPOPXLZ2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APIFORAPPVECIRRPOPXLZ2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APIFORAPPVECIRRPOPXLZ2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.APIFORAPPVECIRRPOPXLZ2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APIFORAPPVECIRRPOPXLZ2_REGISTRY_PASSWORD }}
          containerAppName: apiforapp-vecirrpopxlz2
          resourceGroup: frameworksangularbe9a
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


